# Generated by Django 6.0.4 on 2026-04-21 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
